#ifndef PORTS_H
#define PORTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f3xx_hal_gpio.h"

#define SERVO_PWM_PIN GPIO_PIN_3
#define SERVO_PWM_GPIO_PORT GPIOC
#define SENSOR_PIN GPIO_PIN_0
#define SENSOR_GPIO_PORT GPIOA
#define DEBUG_LED_PIN GPIO_PIN_1
#define DEBUG_LED_GPIO_PORT GPIOA
#define SERVO_CURRENT_PIN GPIO_PIN_2
#define SERVO_CURRENT_GPIO_PORT GPIOA
#define BAT_VOLTAGE_PIN GPIO_PIN_3
#define BAT_VOLTAGE_GPIO_PORT GPIOA
#define VCC_SERVO_VOLTAGE_PIN GPIO_PIN_4
#define VCC_SERVO_VOLTAGE_GPIO_PORT GPIOA
#define H_BRIDGE_VPROP_PIN GPIO_PIN_5
#define H_BRIDGE_VPROP_GPIO_PORT GPIOA
#define H_BRIDGE_ENABLE_PIN GPIO_PIN_6
#define H_BRIDGE_ENABLE_GPIO_PORT GPIOA
#define H_BRIDGE_MODE1_PIN GPIO_PIN_7
#define H_BRIDGE_MODE1_GPIO_PORT GPIOA
#define H_BRIDGE_MODE2_PIN GPIO_PIN_4
#define H_BRIDGE_MODE2_GPIO_PORT GPIOC
#define H_BRIDGE_PHASE_PIN GPIO_PIN_5
#define H_BRIDGE_PHASE_GPIO_PORT GPIOC
#define H_BRIDGE_nSLEEP_PIN GPIO_PIN_0
#define H_BRIDGE_nSLEEP_GPIO_PORT GPIOB
#define H_BRIDGE_nFAULT_PIN GPIO_PIN_1
#define H_BRIDGE_nFAULT_GPIO_PORT GPIOB
#define SPI3_NSS_PIN GPIO_PIN_2
#define SPI3_NSS_GPIO_PORT GPIOD
#define SPI3_SCK_GPIO_PORT GPIOC
#define SPI3_SCK_PIN GPIO_PIN_10
#define SPI3_MISO_PIN GPIO_PIN_11
#define SPI3_MOSI_PIN GPIO_PIN_12
#define I2C1_SCL_GPIO_PORT GPIOB
#define I2C1_SCL_PIN GPIO_PIN_6
#define I2C1_SDA_PIN GPIO_PIN_7
#define I2C3_SCL_PORT GPIOA
#define I2C3_SCL_PIN GPIO_PIN_8
#define I2C3_SDA_PORT GPIOC
#define I2C3_SDA_PIN GPIO_PIN_9

#ifdef __cplusplus
}
#endif

#endif /* PORTS_H */
