<?xml version="1.0"?>
<robot name="rover_wheels" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="rover_wheels" params="config_file">
    <!-- ********** -->
    <!-- Parameters -->
    <!-- ********** -->

    <xacro:property name="degrees_90" value="1.5708"/>

    <xacro:property name="config" value="${xacro.load_yaml(config_file)}"/>
    <xacro:property name="chassis_width" value="${config['kinematics']['axle_width']}"/>
    <xacro:property name="wheelbase" value="${config['kinematics']['l']}"/>
    <xacro:property name="wheel_radius" value="${config['tire']['radius']}"/>
    <xacro:property name="wheel_diameter" value="${wheel_radius * 2}"/>

    <xacro:property name="wheel_width" value="${config['tire']['width']}"/>
    <xacro:property name="wheel_mass" value="${config['tire']['mass']}"/>
    <xacro:property name="wheel_friction_mu1" value="${config['wheel_friction']['mu1']}"/>
    <xacro:property name="wheel_friction_mu2" value="${config['wheel_friction']['mu2']}"/>
    <xacro:property name="wheel_friction_kp" value="${config['wheel_friction']['kp']}"/>
    <xacro:property name="steering_hinge_mass" value="${config['wheel_steering']['hinge_mass']}"/>
    <xacro:property name="steering_velocity" value="${config['wheel_steering']['velocity_limit']}"/>

    <!-- ***************** -->
    <!-- Wheel description -->
    <!-- ***************** -->

    <xacro:macro name="wheel" params="lr_prefix fr_prefix">
      <link name="${lr_prefix}_${fr_prefix}_wheel">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_mass}"/>
          <inertia ixx="0.3" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.2"/>
        </inertial>

        <collision>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>

        <!-- Rendering -->
        <visual>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="wheel_black">
            <color rgba="0.05 0.05 0.05 1.0"/>
          </material>
        </visual>
      </link>

      <gazebo reference="${lr_prefix}_${fr_prefix}_wheel">
        <material>Gazebo/Black</material>
        <mu1>${wheel_friction_mu1}</mu1>
        <mu2>${wheel_friction_mu2}</mu2>
        <!-- <minDepth>0.005</minDepth> -->
        <kp>${wheel_friction_kp}</kp>
      </gazebo>
    </xacro:macro>

    <!-- ********************************* -->
    <!-- Front and rear wheel descriptions -->
    <!-- ********************************* -->

    <!-- Description of how a front wheel is connected to the chassis -->
    <xacro:macro name="front_wheel" params="lr_prefix lr_reflect">
      <!-- 1. Steering hinge link FIRST -->
      <link name="${lr_prefix}_steering_hinge">
        <inertial>
          <origin xyz="0 0 0"/>
          <mass value="${steering_hinge_mass}"/>
          <inertia ixx="0.04" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.04"/>
        </inertial>
      </link>

      <!-- 2. Wheel link -->
      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>

      <!-- 3. Steering joint -->
      <joint name="${lr_prefix}_steering_hinge_joint" type="revolute">
        <origin xyz="${wheelbase/2}
                ${lr_reflect*((chassis_width-wheel_width)/2)}
                ${-wheel_radius}"/>
        <parent link="chassis"/>
        <child link="${lr_prefix}_steering_hinge"/>
        <axis xyz="0 0 1"/>
        <limit lower="${config['input_ranges']['steering']['min']}" upper="${config['input_ranges']['steering']['max']}" effort="10000000" velocity="${steering_velocity}"/>
      </joint>

      <!-- 4. Wheel rotation joint -->
      <joint name="front_${lr_prefix}_wheel_joint" type="continuous">
        <parent link="${lr_prefix}_steering_hinge"/>
        <child link="${lr_prefix}_front_wheel"/>
        <axis xyz="0 1 0"/>
        <limit effort="10000000" velocity="${steering_velocity}"/>
      </joint>
    </xacro:macro>
    <!-- Description of how a rear wheel is connected to the chassis -->
    <xacro:macro name="rear_wheel" params="lr_prefix lr_reflect">
      <!-- 1. Wheel link -->
      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>

      <!-- 2. Wheel joint -->
      <joint name="rear_${lr_prefix}_wheel_joint" type="continuous">
        <origin xyz="${-wheelbase/2}
                    ${lr_reflect*((chassis_width-wheel_width)/2)}
                    ${-wheel_radius}"/>
        <parent link="chassis"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <axis xyz="0 1 0"/>
        <limit effort="10000000" velocity="${steering_velocity}"/>
      </joint>
    </xacro:macro>

    <!-- ************** -->
    <!-- Add the wheels -->
    <!-- ************** -->

    <xacro:front_wheel lr_prefix="left" lr_reflect="1"/>
    <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>

    <xacro:rear_wheel lr_prefix="left" lr_reflect="1"/>
    <xacro:rear_wheel lr_prefix="right" lr_reflect="-1"/>
  </xacro:macro>
</robot>
