name: Build Firmware
description: Build the Rover's firmware

outputs:
  release:
    description: release zip file
    value: ${{ steps.release.outputs.release }}

runs:
  using: composite
  steps:

    - name: Bootstrap repository
      uses: ./.github/actions/bootstrap

    - name: Build source
      run: meson compile -C build
      shell: bash

    - name: Run tests
      run: meson test -v -C build
      shell: bash

    - name: Check source
      run: meson compile -C build check
      shell: bash

    - run: echo "release=$(ls build/rover-release*.zip)" >> $GITHUB_OUTPUT
      id: release
      shell: bash
