name: Build ROS gateway
description: Build the Rover's ROS gateway

inputs:
  push:
    description: push the docker container to GHCR
    required: false

  ros_distro:
    description: target ROS distro name
    required: false
    default: ''

  tags:
    description: docker container tags, space separated
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    # Set up builder outside of script to use this action's built-in caching
    - uses: docker/setup-buildx-action@v3
      id: builder

    - name: Build docker image
      run: |
        args=()
        if [[ "${{ inputs.push }}" == "true" ]]; then
          args+=(--push)
        fi
        if [[ -n "${{ inputs.ros_distro }}" ]]; then
          args+=(--ros-distro "${{ inputs.ros_distro }}")
        fi
        if [[ -n "${{ inputs.tags }}" ]]; then
          args+=(--version-tags "${{ inputs.tags }}")
        fi
        if [[ -n "${{ steps.builder.outputs.name }}" ]]; then
          args+=(--builder "${{ steps.builder.outputs.name }}")
        fi
        ./scripts/build-ros-gateway.sh "${args[@]}"
      shell: bash
