#ifndef PORTS_H
#define PORTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f3xx_hal.h"

#define SERVO_PWM_Pin GPIO_PIN_3
#define SERVO_PWM_GPIO_Port GPIOC
#define SENSOR_POWER_Pin GPIO_PIN_0
#define SENSOR_POWER_GPIO_Port GPIOA
#define DEBUG_LED_Pin GPIO_PIN_1
#define DEBUG_LED_GPIO_Port GPIOA
#define SERVO_CURRENT_Pin GPIO_PIN_2
#define SERVO_CURRENT_GPIO_Port GPIOA
#define BAT_VOLTAGE_Pin GPIO_PIN_3
#define BAT_VOLTAGE_GPIO_Port GPIOA
#define VCC_SERVO_VOLTAGE_Pin GPIO_PIN_4
#define VCC_SERVO_VOLTAGE_GPIO_Port GPIOA
#define H_BRIDGE_VPROP_Pin GPIO_PIN_5
#define H_BRIDGE_VPROP_GPIO_Port GPIOA
#define H_BRIDGE_ENABLE_Pin GPIO_PIN_6
#define H_BRIDGE_ENABLE_GPIO_Port GPIOA
#define H_BRIDGE_MODE1_Pin GPIO_PIN_7
#define H_BRIDGE_MODE1_GPIO_Port GPIOA
#define H_BRIDDGE_MODE2_Pin GPIO_PIN_4
#define H_BRIDDGE_MODE2_GPIO_Port GPIOC
#define H_BRIDGE_PHASE_Pin GPIO_PIN_5
#define H_BRIDGE_PHASE_GPIO_Port GPIOC
#define H_BRIDGE_nSLEEP_Pin GPIO_PIN_0
#define H_BRIDGE_nSLEEP_GPIO_Port GPIOB
#define H_BRIDGE_nFAULT_Pin GPIO_PIN_1
#define H_BRIDGE_nFAULT_GPIO_Port GPIOB
#define SPI3_NSS_Pin GPIO_PIN_2
#define SPI3_NSS_GPIO_Port GPIOD

#ifdef __cplusplus
}
#endif

#endif /* PORTS_H */
