name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache python venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Cache meson subprojects
        uses: actions/cache@v4
        with:
          path: subprojects
          key: meson-${{ runner.os }}-${{ hashFiles('subprojects/*.wrap') }}-${{ hashFiles('subprojects/packagefiles/**') }}

      # Will run pip
      - name: Bootstrap build
        run: ./scripts/bootstrap.sh

      - name: Activate python venv
        run: |
          source .venv/bin/activate
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Build source
        run: meson compile -C build

      - name: Run tests
        run: meson test -v -C build

      - name: Check source
        run: meson compile -C build check

      - name: Build documentation
        run: meson compile -C build docs

      - name: Build release
        run: meson compile -C build release
