name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      # Will run pip
      - name: Bootstrap build
        run: ./scripts/bootstrap.sh

      - name: Build source
        run: meson compile -C build

      - name: Run tests
        run: meson test -v -C build

      - name: Check source
        run: ./scripts/check-src.sh

      - name: Build documentation
        run: meson compile -C build docs

      - name: Build release
        run: meson compile -C build release
