name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: bootstrap
        run: ./scripts/bootstrap

      - name: code checks
        run: |
          shfmt -d .
          shfmt -f . | xargs shellcheck -o all
          yamlfmt -lint .
          ninja -C build clang-format-check

      - name: make check
        run: make check

      - name: make distcheck
        run: make distcheck
