name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          # Need to add packages manually from bootstrap script
          packages: |
            curl
            clang-format
            clang-tidy
            gcc-arm-none-eabi
            libc6-dev-armhf-cross
            meson
            ninja-build
            shellcheck
            shfmt

      - name: Bootstrap build
        run: ./scripts/bootstrap.sh

      - name: Build source
        run: ninja -C build

      - name: Check source
        run: ./scripts/check-src.sh
