name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      # Will run pip
      - name: Bootstrap build
        run: ./scripts/bootstrap.sh

      - name: Build source
        run: meson compile -C build

      - name: Run tests
        run: meson test -v -C build

      - name: Check source
        run: ./scripts/check-src.sh

      - name: Cache assets
        id: cache-assets
        uses: actions/cache@v3
        with:
          path: docs/_assets
          key: ${{ runner.os }}-assets

      - name: Build documentation
        run: meson compile -C build docs

    # - name: Deploy documentation to GH Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: ${{ github.ref == 'refs/heads/main' }}
    #   with:
    #     publish_branch: gh-pages
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: build/docs/html
    #     force_orphan: true
